// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skincare.BusinessObjects.Entities;

public partial class Account
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string Avatar { get; set; }

    public string PhoneNumber { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string Role { get; set; }

    public string PasswordHash { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? RefreshTokenExpiry { get; set; }

    public string OtpCode { get; set; }

    public DateTime? OtpExpiry { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}