// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;


namespace Skincare.BusinessObjects.Entities;

public partial class Account
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    [Column(TypeName = "nvarchar(MAX)")]
    public string Avatar { get; set; }

    public string PhoneNumber { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string Role { get; set; }

    public string PasswordHash { get; set; }

    public virtual ICollection<BlogPost> BlogPosts { get; set; } = new List<BlogPost>();

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<CustomerTest> CustomerTests { get; set; } = new List<CustomerTest>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<SkinCareRoutine> SkinCareRoutines { get; set; } = new List<SkinCareRoutine>();
}