// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skincare.BusinessObjects.Entities;

public partial class BlogPost
{
    public int Id { get; set; }

    public int BlogOwnerId { get; set; }

    public int BlogCategoryId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string Img { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsVisible { get; set; }

    public virtual BlogCategory BlogCategory { get; set; }

    public virtual Account BlogOwner { get; set; }
}