// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skincare.BusinessObjects.Entities;

public partial class Order
{
    public int Id { get; set; }

    public int CustomerId { get; set; }

    public int? VoucherId { get; set; }

    public decimal TotalPrice { get; set; }

    public decimal? DiscountPrice { get; set; }

    public bool IsPrepaid { get; set; }

    public string Status { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Account Customer { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual OrderStatus StatusNavigation { get; set; }

    public virtual Voucher Voucher { get; set; }
}