// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skincare.BusinessObjects.Entities;

public partial class Qa
{
    public int Id { get; set; }

    public string Question { get; set; }

    public string Answer { get; set; }

    public DateTime? LastUpdateAt { get; set; }

    public bool IsVisible { get; set; }
}