// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skincare.BusinessObjects.Entities;

public partial class Review
{
    public int Id { get; set; }

    public int OrderDetailId { get; set; }

    public int CustomerId { get; set; }

    public int? Rating { get; set; }

    public string Comment { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int ProductId { get; set; }


    public virtual Account Customer { get; set; }

    public virtual OrderItem OrderDetail { get; set; }

    public virtual Product Product { get; set; }
}