// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skincare.BusinessObjects.Entities;

public partial class SkinCareRoutine
{
    public int Id { get; set; }

    public int CustomerId { get; set; }

    public int SkinTypeId { get; set; }

    public string RoutineSteps { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Account Customer { get; set; }

    public virtual SkinType SkinType { get; set; }
}