// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skincare.BusinessObjects.Entities;

public partial class SkinType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int Score { get; set; }

    public virtual ICollection<SkinCareRoutine> SkinCareRoutines { get; set; } = new List<SkinCareRoutine>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}