// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skincare.BusinessObjects.Entities;

public partial class Test
{
    public int Id { get; set; }

    public string Title { get; set; }

    public virtual ICollection<CustomerTest> CustomerTests { get; set; } = new List<CustomerTest>();

    public virtual ICollection<Quiz> Quizzes { get; set; } = new List<Quiz>();
}