// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skincare.BusinessObjects.Entities;

public partial class Transaction
{
    public int TransactionId { get; set; }

    public int OrderId { get; set; }

    public string PaymentMethod { get; set; }

    public string Status { get; set; }

    public decimal Amount { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual Order Order { get; set; }
}