// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skincare.BusinessObjects.Entities;

public partial class Voucher
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool IsPercent { get; set; }

    public string Code { get; set; }

    public decimal? MinOrderValue { get; set; }

    public decimal Value { get; set; }

    public decimal? MaxDiscountValue { get; set; }

    public DateTime StartedAt { get; set; }

    public DateTime? ExpiredAt { get; set; }

    public bool? IsInfinity { get; set; }

    public int Quantity { get; set; }

    public int PointCost { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}