// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skincare.Repositories.Models;

public partial class Account
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string Avatar { get; set; }

    public string PhoneNumber { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string Role { get; set; }

    public string PasswordHash { get; set; }
}