// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skincare.Repositories.Models;

public partial class ProductSkinType
{
    public int ProductId { get; set; }

    public int SkinTypeId { get; set; }

    public int Id { get; set; }
}